# Generated by Django 4.0.5 on 2022-07-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entrenador', models.CharField(max_length=60)),
                ('numero_entrenador', models.CharField(max_length=60)),
                ('ciudad_entrenador', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='gimnasio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gimnasio', models.CharField(max_length=60)),
                ('ciudad_gimnasio', models.CharField(max_length=60)),
                ('cantidad_habitantes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Efec', models.CharField(max_length=300)),
                ('porcentaje', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=20)),
                ('Peso', models.FloatField()),
                ('Numero', models.IntegerField()),
                ('Nombre_pokemon', models.CharField(max_length=60)),
                ('Fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='pokemonEst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atk', models.IntegerField()),
                ('Def', models.IntegerField()),
                ('Spd', models.IntegerField()),
            ],
        ),
    ]
